using System;
using System.Collections.Generic;

namespace Concurrency.Interface.Models
{
    //TODO: Build Compare to be able to sort on BID
    [Serializable]
    public record SubBatch   // sent from global coordinator to local coordinator
    {
        public long Bid { get; init; }

        public long CoordinatorId { get; set; }

        public long PreviousBid { get; set; }

        public List<long> Transactions { get; init; }

        // NOTICE: this field is only used for batches generated by local coordinators
        public long PreviousRegionalBid { get; set; }

        public SubBatch(long bid, long coordinatorId)
        {
            this.PreviousBid = -1;
            this.Bid = bid;
            this.CoordinatorId = coordinatorId;
            this.Transactions = new List<long>();
            this.PreviousRegionalBid = -1;
        }

        public SubBatch(SubBatch subBatch)
        {
            this.Bid = subBatch.Bid;
            this.CoordinatorId = subBatch.CoordinatorId;
            this.PreviousBid = subBatch.PreviousBid;
            this.Transactions = subBatch.Transactions;
            this.PreviousRegionalBid = subBatch.PreviousRegionalBid;
        }

        public override string ToString()
        {
            return $"Bid: {this.Bid}, PreviousBid: {this.PreviousBid}, LocalCoordinatorId: {this.CoordinatorId}, previousRegionalBid: {PreviousRegionalBid}, Transactions: [{string.Join(", ", this.Transactions)}]";
        }
    }
}